### PR TITLE
Improve the regeneration of Java binding

### PR DESCRIPTION
**Pull request by yvanzo**
## Problem

The regeneration of the Java binding was requiring:
* some manual steps made of running commands and editing files, and
* the prerequisites (JDK, Maven, and Trang) to be installed on the developer’s system,
  with the main inconvenient of different versions producing different results.

## Solution

1. Replace each file editing step with a patch script.
2. Replace all the steps with one script to run these all.
3. Use Docker Compose to install the prerequisites reproduceably,
   and to regenerate the Java binding, all by running a single command.

### CODE REVIEW

**Comment by reosarevok** [comment]
Tried to run this and got:

```
Done generating Java classes.
Patching the generated Java class files...
* DiscList.java
* Medium.java
* MediumList.java
Done patching Java classes.
Restoring files changed by timestamp only...
warning: Not a git repository. Use --no-index to compare two paths outside a working tree
usage: git diff --no-index [<options>] <path> <path>

[...]

fatal: detected dubious ownership in repository at '/code'
To add an exception for this directory, call:

	git config --global --add safe.directory /code

ERROR: 128
```

It might be I did something dumb, but :)

**Comment by yvanzo** [comment]
> Tried to run this and got:
> 
> ```
> warning: Not a git repository. Use --no-index to compare two paths outside a working tree
> usage: git diff --no-index [<options>] <path> <path>
> ```

Did you run it from a git clone?

> ```
> fatal: detected dubious ownership in repository at '/code'
> ```

You can see file ownerships by running the container with `ls -All /code`.
Only `..` should belong to `root` user/group, other files should belong to your host user/group IDs.
That is unless your Docker system is running in a mode that maps file ownerships differently.

> ```
> To add an exception for this directory, call:
> 
> 	git config --global --add safe.directory /code
> ```

This exception should have already been added through the Dockerfile, see https://github.com/metabrainz/mmd-schema/pull/35/files#diff-59b0100027b63a7e9f32d3919dcca590ff51366dc8bcb4b140d37c3d61cbf4a3R10-R14

You can check that this file exists indeed by running the container with `cat ~/.gitconfig`.

**Comment by mwiencek** [comment]
It seems to work flawlessly for me. 👍 I tested running it without any changes (a no-op), then with a random change to the MMD schema (which produced the expected binding changes), then again with the MMD changes reverted (which reverted the binding changes).

**Comment by amCap1712** [comment]
Works for me as well, Thanks!

**Pull request merged**
